# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6b8091e110f80f9e1dcf98222b2f743"
name = "vercel-testing"
handle = "vercel-testing"
application_url = "https://decrease-helped-sender-done.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://decrease-helped-sender-done.trycloudflare.com/auth/callback", "https://decrease-helped-sender-done.trycloudflare.com/auth/shopify/callback", "https://decrease-helped-sender-done.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
